{% set name = "jsonpath" %}
{% set version = "0.82" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46d3fd2016cd5b842283d547877a02c418a0fe9aa7a6b0ae344115a2c990fef4
  patches:
    - patches/0001-rm-test-jsonpath-py.patch
    - patches/0002-safe-eval.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - test
  imports:
    - jsonpath
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v test/test1.py test/test2.py test/test3.py test/test4.py

about:
  home: https://www.ultimate.com/phil/python/#jsonpath
  license: MIT
  license_family: MIT
  # conda-forge created LICENSE.txt but the actual license statement
  # is in jsonpath.py
  license_file: LICENSE.txt
  summary: An XPath for JSON
  description: |
    A port of the Perl, and JavaScript versions of JSONPath
  doc_url: https://goessner.net/articles/JsonPath/
  dev_url: https://www.ultimate.com/phil/python/#jsonpath

extra:
  recipe-maintainers:
    - hoishing
