travis:
  secure:
    BINSTAR_TOKEN: QPlu91IGVeKeOyy7vSkxizNLgLN8yxn7Qn+1rSZwZp8Dk9iyp7Wara6oBicwSdaDieNV1HujJota4GaQQkpbQlp5BM8H9grIyzP4LA5pyyGFXv8bfSDIRtNDpB024YfCh89SZDO/5Zd99ARh+AdeseQWIhiwsqM+oZm8w/AseGoTR9hdNnJC6zYbMe9crKjYZ2Vmre8U9J7I6vs7uTVw7K1gQlzZDj0Ozi6F9ispNIdFqqYJucOnSt0CaOl6HAwVeBCVJV45OJvmc2UKLPmro9sdH24w+y8IOlEmNB7QCu8tjhav1iyhiqpvvHv74VQz6wwdTv1vbcJzOHAJOVXUVz3J3xlb73Uxpt5T6z/DFrFbw9Res+txnU+pit4fiiRpsHIvxpcQ7cIw4R65yLP5UMVQOQ1FvNbQavOq65EKjVwGMsoBcty37LPiYCKIzQZJ1eyKns05Vu6TRatkk6GA1pyFV0qX6qm+wIAabSzqqRDYXN4WmF16c25HIjum4E8wofo+Tc9a7NDPyH+3b84q4yuG4oFo7Wl2mUdj6nVC08mWyiG1mFifnndrv2TEQHwnVGYiSdwL4FZxCH8bPI5Vzlbj0OVTjKAJANEN5kNPwveQdhqitc26981B92WNJ/vHBey9DH00g3AYTSQGBp2L1PMzuLCzqeMzgyBsglBe+Rs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
